{% set name = "outlier-utils" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace("-", "_") }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 16e46fa6f7b01fe5518ea73fc15d3de0e30091750c428760bbe7dde2c9590579

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 1

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - numpy
    - scipy

test:
  imports:
    - outliers

about:
  home: https://github.com/c-bata/outlier-utils
  summary: 'Library for detecting and removing outliers from normally distributed datasets'
  description: |
    Library for detecting and removing outliers from normally distributed
    datasets using the Smirnov-Grubbs test.
    Both the two-sided and the one-sided version of the test are supported. 
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bernt-matthias
